### PR TITLE
Upgrade to valid v1.0 CWL

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by denis-yuen** [comment]
@mr-c FYI, running into some build issues https://travis-ci.org/CancerCollaboratory/dockstore-tool-bamstats/builds/174724645  
Not sure why they aren't being linked here

**Comment by denis-yuen** [comment]
@mr-c  Could you allow upstream maintainers to modify this, I might have an idea https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by mr-c** [comment]
@denis-yuen Already enabled :-)

**Comment by denis-yuen** [comment]
@mr-c  Hmmm, looks like change succeeded. but it doesn't seem to be very practical. From a CWL perspective, do you happen to know why the format would be needed in the input.json file now? (It doesn't seem like your change should have affected this and we didn't change the version of cwltool or its dependencies)

**Comment by denis-yuen** [comment]
@tetron Any thoughts on this one?
It looks like something about these changes makes adding the format to the parameter json necessary when it appears in the CWL file (whereas it doesn't seem to have been necessary in the past, ex: https://travis-ci.org/CancerCollaboratory/dockstore-tool-bamstats/builds/159983666 ).

Is this an expected/desired change? Looking at the user guide and CommandLineTool document, I don't really find enlightenment on this either way.

**Comment by mr-c** [comment]
@denis-yuen File format matching is optional and the reference implementation does it by default. We have an open issue to add a flag to change the behaviour https://github.com/common-workflow-language/cwltool/issues/217

**Comment by denis-yuen** [comment]
@mr-c do you happen to know when file format matching was added? Was this added in cwltool or in a dependency that we didn't lock down?

**Comment by mr-c** [comment]
@denis-yuen Some testing shows that it is the presence of the `$schema` section I added that triggered the different behavior.

I still recommend making the CWL descriptions not need `--non-strict`

**Comment by denis-yuen** [comment]
@mr-c  Ah, $schema. I totally wouldn't have guessed that. 

I think we're going to need to update the Dockstore CLI to either create these format fields in the JSON parameter file and (ideally)/or(less ideally) update to a version of cwltool that makes format checking optional, so I'm going to add that section back when we have that work complete.

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
